# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:title.html

# Setup
title:            "WTF | PDQuin"
tagline:          "Write | Teach | Format | The arc of a working life"
url:              https://github.com/pdquin/pdquin.github.io
paginate:         5
baseurl:          /
author:
  name:           Paul D Quin
  url:            https://twitter.com/pdquin
  email:          paul.d.quin@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/pdquin/pdquin.github.io
