# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /:title.html

# Setup
title:            "WTF | PDQuin"
tagline:          "Write | Teach | Format | The arc of a working life"
url:              https://github.com/pdquin/pdquin.github.io.git
paginate:         1
baseurl:          /
author:
  name:           Paul D Quin
  url:            http://pdquin.com/
  email:          himself@pdquin.com

# Custom vars
version:          1.0.0
github:
  repo:           

