# Site settings
title: WTF PDQ Write + Teach + Format
email: himself@pdquin.com
description: "The arc of a working life :: Geeky hows for designers + writing/design trials + random notes"
baseurl: ""
url: "http://wtf.pdquin.com"

# Build settings
markdown: kramdown
permalink: pretty
